application: myuniversalplayer
version: 20120909
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: Ressources/stylesheets
- url: /images
  static_dir: Ressources/images
- url: /javascripts
  static_dir: Ressources/javascripts
- url: /.*
  script: Routeur.app


libraries:
- name: jinja2
  version: latest